export * from './course.interface'
export * from './education.interface'
export * from './experience.interface'
export * from './general.interface'
export * from './links.interface'
export * from './project.interface'
export * from './recommendation.interface'
export * from './user.interface'
