import type { Metadata } from 'next'
import { ThemeProvider, FontsProvider, NextUIProvider } from './_shared/providers/index'
import '@styles/index.css'

type Props = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Jorge Vargas | Portfolio!',
  description: 'Generated by create next app'
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <ThemeProvider>
      <FontsProvider>
        <NextUIProvider>{children}</NextUIProvider>
      </FontsProvider>
    </ThemeProvider>
  )
}

export default RootLayout
