import type { Metadata } from 'next'
import { ThemeProvider, FontsProvider, NextUIProvider } from './_shared/providers/index'
import '@styles/index.css'

type Props = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Jorge Vargas | Portfolio!',
  description: 'Generated by create next app',
  icons: [
    {
      url: '/favicon.ico',
      rel: 'icon'
    },
    {
      url: '/seo.webp',
      rel: 'apple-touch-icon',
      sizes: '180x180'
    }
  ],
  openGraph: {
    images: [
      {
        url: '/seo.webp',
        width: 850,
        height: 650,
        alt: 'Og Image Alt'
      }
    ]
  }
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <ThemeProvider>
      <FontsProvider>
        <NextUIProvider>{children}</NextUIProvider>
      </FontsProvider>
    </ThemeProvider>
  )
}

export default RootLayout
