import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import '@styles/index.css'
import Providers from '@providers/index'

const poppins = Poppins({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

type Props = {
  children: React.ReactNode
}

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang='en' className='dark'>
      <body className={poppins.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}

export default RootLayout
